### ISSUE TITLE
Some current issues

### ISSUE THREAD

**Issue by turgeonmaxime** [margothenry/PloidyPeaks#1]
I know you're still developing the package, but here are a few issues I noted.

- [x] To use the MIT license, you need to add a `LICENSE` file at the root of your package with your name and the current year. See for example this package of mine: https://github.com/UMDimReduction/GenSoftImpute
- [x] To use the pipe `%>%`, you'll need to import it to your NAMESPACE, otherwise it won't work. You can do this by running the code `usethis::use_pipe()`; see this: https://usethis.r-lib.org/reference/use_pipe.html
- [x] The `vignette` directory should actually be `vignettes`, otherwise it throws a warning.

In RStudio, if you run `devtools::check()` (or click on "Check" under the "Build" panel), you'll see there's a few warnings and notes, which you will have to address. But most of them are actually related to what we discussed about using `::` to call functions from packages under "Imports" in your DESCRIPTION file.

If I note anything else, I'll open another issue, so feel free to close this one once you've addressed the points above!

**Comment by margothenry** [comment]
All Issues have been fixed, thank you!
