### ISSUE TITLE
Proper format for vignette

### ISSUE THREAD

**Issue by turgeonmaxime** [margothenry/PloidyPeaks#2]
There's a few more hoops for the vignette.

- [x] The first thing you'll need to do is change the YAML header at the top of your vignette so that it matches what is described here: https://r-pkgs.org/vignettes.html#vignette-metadata.
- [x] You may also want to change the name of the file to something more informative 😅 
- [x] On Line 11, you are installing the `PloidyPeaks` package. You should remove that line. Indeed, users should already have installed your package, so it is unnecessary. 
- [x] Make sure all the packages you are attaching in the setup chunk are actually necessary (because of the next point). In particular, `tcltk` can be tricky to install for users on MacOS and Linux, so if you don't need it, remove it!
- [x] All packages you are attaching in your vignette must be either in Imports or Suggests in your DESCRIPTION file. The idea is if you only need a particular package for the vignette, it should go in Suggests. If you need a package to make your own package work, it should go in Imports.
- [x] Finally, everywhere you use `here("vignette/data/gated_data")` (or similarly for images), you should simply write "data/gated_data". Otherwise it could cause issues when installing the package, because the directory structure actually changes when your package is installed. And as a bonus, you won't need the `here` package for your vignette anymore!

**Comment by margothenry** [comment]
done!
